service: cpsia-certificates # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  cpsia:
    handler: handler.endpoint
    events:
      - http:
          path: cpsia/{brand}/{business}
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true
                business: true