service: goalrilla-quote-api # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  postQuoteRequest:
    handler: handler.postQuoteRequest
    events:
      - http:
          path: quote
          method: post
          cors: true