service: customer-service-api # NOTE: update this with your service name

custom:
  secrets: ${file(env.yml):prod}
  defaultStage: dev
  defaultProfile: default

provider:
  name: aws
  runtime: nodejs6.10
  stage: "${opt:stage, self:custom.defaultStage}"
  region: us-east-2
  environment:
    STAGE: ${self:provider.stage}
    PROFILE: ${self:custom.defaultProfile}
    SPARKPOST_API_KEY: "${self:custom.secrets.SPARKPOST_API_KEY}"
    GOOGLE_SHEETS_API_KEY: "${self:custom.secrets.GOOGLE_SHEETS_API_KEY}"
    GOOGLE_SHEETS_CLIENT_EMAIL: "${self:custom.secrets.GOOGLE_SHEETS_CLIENT_EMAIL}"

plugins:
  - serverless-offline

functions:
  postWarrantyClaim:
    handler: handler.postWarrantyClaim
    events:
      - http:
          path: warranty-claims
          method: post
          cors: true
  postContact:
    handler: handler.postContact
    events:
      - http:
          path: contact
          method: post
          cors: true
