service: escalade-manuals # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs6.10

plugins:
  - serverless-offline

functions:
  manuals:
    handler: handler.endpoint
    events:
      - http:
          path: manuals/{brand}
          method: get
          cors: true
          request:
            parameters:
              paths:
                brand: true
                business: true